project:
  type: website

execute: 
  echo: true
  fig-width: 10
  fig-height: 4.5

website:
  page-navigation: true
  title: "IME05-06471"
  description: "Teoria da Decisão Estatística"

  twitter-card:
    creator: "@r_accioly"
    image: "images/tde.png"

  page-footer:
    left: "Baseado em https://sta210-s22.github.io/website/"
    background: "#D9E3E4"

  sidebar:
    background: "#D9E3E4"
    logo: "images/tde.png"
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/raccioly20
        text: "GitHub"
      - icon: twitter
        href: https://twitter.com/r_accioly
        text: "Twitter"    

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Informação da disciplina"
        contents:
          - href: index.qmd
            text: Topicos
      - section: "Sobre"
        contents:
          - href: about.qmd
            text: Sobre
      - section: "Topicos"
        contents:
          - href: estudos_de_caso/exe01.qmd
            text: "Exemplo01"
          - href: estudos_de_caso/exe02.qmd
            text: "Exemplo02"
 
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

freeze: auto

editor: visual

